DROP FUNCTION IF EXISTS gamebox_agent_rakeback();
DROP FUNCTION IF EXISTS gamebox_agent_statement(date, json);
DROP FUNCTION IF EXISTS gamebox_backwater(text, text, text, text, int);
DROP FUNCTION IF EXISTS gamebox_collect_site_infor(text, int);
DROP FUNCTION IF EXISTS gamebox_current_site();
DROP FUNCTION IF EXISTS gamebox_expense(hstore, hstore, hstore, int, text, text);
DROP FUNCTION IF EXISTS gamebox_expense_allocation(int4, timestamp, timestamp, text, text);
DROP FUNCTION IF EXISTS gamebox_expense_calculate(hstore, hstore, text);
DROP FUNCTION IF EXISTS gamebox_expense_gather(timestamp, timestamp);
DROP FUNCTION IF EXISTS gamebox_expense_gather(timestamp, timestamp, text);
DROP FUNCTION IF EXISTS gamebox_expense_gather(timestamp, timestamp, text, text);
DROP FUNCTION IF EXISTS gamebox_expense_map(timestamp, timestamp, hstore);
DROP FUNCTION IF EXISTS gamebox_expense_share(hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_generate_order_no(text, text, text);
DROP FUNCTION IF EXISTS gamebox_occupy(text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_occupy(text, text, text, text, int);
DROP FUNCTION IF EXISTS gamebox_occupy_agent(int4);
DROP FUNCTION IF EXISTS gamebox_occupy_api(int4, timestamp, timestamp, hstore, hstore, hstore, hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_occupy_api_calculator(hstore, hstore, int, int, int, text, float);
DROP FUNCTION IF EXISTS gamebox_occupy_api_map(timestamp, timestamp, hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_occupy_api_set();
DROP FUNCTION IF EXISTS gamebox_occupy_bill(text, timestamp, timestamp, int, text);
DROP FUNCTION IF EXISTS gamebox_occupy_calculator(hstore, hstore, json);
DROP FUNCTION IF EXISTS gamebox_occupy_expense(hstore, hstore, hstore, int);
DROP FUNCTION IF EXISTS gamebox_occupy_expense_gather(int, timestamp, timestamp);
DROP FUNCTION IF EXISTS gamebox_occupy_expense_map(timestamp, timestamp, hstore);
DROP FUNCTION IF EXISTS gamebox_occupy_map(text, text, text);
DROP FUNCTION IF EXISTS gamebox_occupy_player(int, hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_occupy_topagent(int);
DROP FUNCTION IF EXISTS gamebox_occupy_value(timestamp, timestamp, hstore);
DROP FUNCTION IF EXISTS gamebox_operation_occupy(timestamp, timestamp, text);
DROP FUNCTION IF EXISTS gamebox_operations_agent(text, json);
DROP FUNCTION IF EXISTS gamebox_operations_occupy(hstore[], timestamp, timestamp, text, int);
DROP FUNCTION IF EXISTS gamebox_operations_occupy(text, int, timestamp, timestamp, text, boolean, int);
DROP FUNCTION IF EXISTS gamebox_operations_occupy(text, timestamp, timestamp, text, int);
DROP FUNCTION IF EXISTS gamebox_operations_occupy_calculate(hstore, json, text);
DROP FUNCTION IF EXISTS gamebox_operations_player(text, text, text, json);
DROP FUNCTION IF EXISTS gamebox_operations_site(text);
DROP FUNCTION IF EXISTS gamebox_operations_statement(text, int, text, text);
DROP FUNCTION IF EXISTS gamebox_operations_topagent(text, json);
DROP FUNCTION IF EXISTS gamebox_player_statement(text, text, date, json);
DROP FUNCTION IF EXISTS gamebox_rakeback(text, text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_rakeback_api(int4, timestamp, timestamp, hstore, hstore, text);
DROP FUNCTION IF EXISTS gamebox_rakeback_api_grads();
DROP FUNCTION IF EXISTS gamebox_rakeback_api_map(timestamp, timestamp, hstore, hstore, text);
DROP FUNCTION IF EXISTS gamebox_rakeback_api_map(timestamp, timestamp, hstore, hstore, text, text);
DROP FUNCTION IF EXISTS gamebox_rakeback_bill(text, timestamp, timestamp, int, text, text);
DROP FUNCTION IF EXISTS gamebox_rakeback_calculator(hstore, hstore, json);
DROP FUNCTION IF EXISTS gamebox_rakeback_limit(int, hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_rakeback_map(timestamp, timestamp, text, text);
DROP FUNCTION IF EXISTS gamebox_rakeback_player(int, hstore, hstore, text);
DROP FUNCTION IF EXISTS gamebox_rakeback_set();
DROP FUNCTION IF EXISTS gamebox_rebate(text, text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_rebate_agent(int, text);
DROP FUNCTION IF EXISTS gamebox_rebate_agent_check(hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_rebate_agent_check(hstore, hstore, timestamp, timestamp);
DROP FUNCTION IF EXISTS gamebox_rebate_agent_default_set();
DROP FUNCTION IF EXISTS gamebox_rebate_api(int, timestamp, timestamp, hstore, hstore, hstore, text);
DROP FUNCTION IF EXISTS gamebox_rebate_api(int, timestamp, timestamp, hstore, hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_rebate_api_grads();
DROP FUNCTION IF EXISTS gamebox_rebate_bill(text, timestamp, timestamp, int, text, text);
DROP FUNCTION IF EXISTS gamebox_rebate_calculator(hstore, hstore, hstore, json);
DROP FUNCTION IF EXISTS gamebox_rebate_calculator(hstore, hstore, int, int, text, float, float);
DROP FUNCTION IF EXISTS gamebox_rebate_expense_gather(int4, hstore, timestamp, timestamp, text, text);
DROP FUNCTION IF EXISTS gamebox_rebate_map(timestamp, timestamp, int, hstore, hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_rebate_map(text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_rebate_player(hstore, hstore, hstore, int, text, text, text);
DROP FUNCTION IF EXISTS gamebox_rebate_rakeback_map(timestamp, timestamp);
DROP FUNCTION IF EXISTS gamebox_site_game(text, text, int, text);
DROP FUNCTION IF EXISTS gamebox_sys_param(text);
DROP FUNCTION IF EXISTS gamebox_topagent_statement(date, json);
DROP FUNCTION IF EXISTS gamebox_rakeback_api(int4, timestamp, timestamp, text);
DROP FUNCTION IF EXISTS gamebox_rakeback_api_base(timestamp);
DROP FUNCTION IF EXISTS gamebox_rakeback_player(int, text);
DROP FUNCTION IF EXISTS gamebox_occupy_rebate_map(TIMESTAMP, TIMESTAMP);
DROP FUNCTION IF EXISTS gamebox_rakeback_calculator(hstore, hstore, json, TIMESTAMP);
DROP FUNCTION IF EXISTS gamebox_rakeback_limit(int, hstore, hstore, float);
-- DROP FUNCTION IF EXISTS
