-- auto gen by marz 2018-01-28 17:24:39
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_34', '50000', '10000', '200000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_34');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_56', '50000', '10000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_56');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_78', '50000', '10000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_78');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_910', '50000', '10000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_910');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_alone_11', '50000', '10000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_alone_11');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_alone_34', '30000', '5000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_alone_34');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_alone_56', '30000', '5000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_alone_56');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_alone_78', '30000', '5000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_alone_78');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_alone_910', '30000', '5000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_alone_910');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_big_small', '100000', '30000', '2000000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_big_small');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_single_double', '100000', '30000', '2000000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_single_double');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'pk10_big_small', '100000', '30000', '2000000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'pk10_big_small');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'pk10_digital', '50000', '10000', '300000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'pk10_digital');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'pk10_dragon_tiger', '50000', '10000', '2000000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'pk10_dragon_tiger');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'pk10_single_double', '100000', '30000', '2000000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'pk10_single_double');
INSERT INTO lottery_quota ("code", "play_code", "num_quota", "bet_quota", "play_quota") SELECT 'jspk10', 'champion_up_half', '100000', '30000', '2000000' WHERE NOT EXISTS (SELECT code FROM lottery_quota WHERE code = 'jspk10' AND play_code = 'champion_up_half');
