-- auto gen by cherry 2018-05-25 20:30:16
DROP VIEW IF EXISTS vv_sys_user;
ALTER TABLE sys_user ALTER COLUMN terminal type varchar(2);

CREATE OR REPLACE VIEW "vv_sys_user" AS
 SELECT sys_user.id,
    sys_user.username,
    md5((sys_user.password)::text) AS password,
    sys_user.dept_id,
    sys_user.status,
    sys_user.create_user,
    sys_user.create_time,
    sys_user.update_user,
    sys_user.update_time,
    sys_user.default_locale,
    sys_user.default_timezone,
    sys_user.subsys_code,
    sys_user.user_type,
    sys_user.built_in,
    sys_user.site_id,
    sys_user.owner_id,
    sys_user.freeze_type,
    sys_user.freeze_start_time,
    sys_user.freeze_end_time,
    sys_user.login_time,
    sys_user.login_ip,
    sys_user.last_active_time,
    sys_user.use_line,
    sys_user.last_login_time,
    sys_user.last_login_ip,
    sys_user.total_online_time,
    sys_user.register_ip,
    sys_user.nickname,
    sys_user.real_name,
    sys_user.birthday,
    sys_user.sex,
    sys_user.constellation,
    sys_user.country,
    sys_user.nation,
    sys_user.avatar_url,
    md5((sys_user.permission_pwd)::text) AS permission_pwd,
    sys_user.idcard,
    sys_user.default_currency,
    sys_user.register_site,
    sys_user.region,
    sys_user.city,
    sys_user.memo,
    sys_user.password_level,
    sys_user.login_ip_dict_code,
    sys_user.last_login_ip_dict_code,
    sys_user.register_ip_dict_code,
    sys_user.login_error_times,
    sys_user.freeze_title,
    sys_user.freeze_content,
    sys_user.freeze_code,
    sys_user.last_logout_time,
    sys_user.freeze_user,
    sys_user.disabled_user,
    sys_user.disabled_time,
    sys_user.freeze_time,
    sys_user.account_freeze_remark,
    sys_user.secpwd_freeze_start_time,
    sys_user.secpwd_freeze_end_time,
    sys_user.secpwd_error_times,
    sys_user.session_key,
    sys_user.terminal,
    md5((sys_user.authentication_key)::text) AS authentication_key
   FROM sys_user;
