-- auto gen by longer 2016-01-07 14:35:46

COMMENT ON TABLE sys_user IS '系统用户--Kevice';
COMMENT ON COLUMN sys_user.id IS '主键';
COMMENT ON COLUMN sys_user.username IS '账号';
COMMENT ON COLUMN sys_user.password IS '用户密码';
COMMENT ON COLUMN sys_user.dept_id IS '部门id';
COMMENT ON COLUMN sys_user.status IS '状态,枚举:SysUserStatus,[1, 正常],[2, 停用],[3, 冻结(不记录表)],[4, 未激活/未审核],[5,审核失败]';
COMMENT ON COLUMN sys_user.create_user IS '创建用户id';
COMMENT ON COLUMN sys_user.create_time IS '创建时间';
COMMENT ON COLUMN sys_user.update_user IS '更新用户id';
COMMENT ON COLUMN sys_user.update_time IS '更新时间';
COMMENT ON COLUMN sys_user.default_locale IS '默认本地化信息：两位小写语言代码_两位大写国家代码,如:en_US';
COMMENT ON COLUMN sys_user.default_timezone IS '默认时区';
COMMENT ON COLUMN sys_user.subsys_code IS '子系统编号: [boss,总控],[ccenter,运营商] [mcenter,站长中心] [mcenterTopAgent,总代] [mcenterAgent,代理] [pcenter,玩家]';
COMMENT ON COLUMN sys_user.user_type IS '用户类型：[0,运维],[01,总控子账号] [1,运营]，[11,运营子账号]，[2,站长]，[21,站长子账号]，[22,总代]，[221,总代子账号]，[23,代理]，[231,代理子账号]，[24,玩家]';
COMMENT ON COLUMN sys_user.built_in IS '是否系统内置';
COMMENT ON COLUMN sys_user.site_id IS '站点ID,此用户所在site的siteId';
COMMENT ON COLUMN sys_user.owner_id IS '所有者id,当user_type=[21 | 22]时,此值必须为空';
COMMENT ON COLUMN sys_user.freeze_type IS '冻结类型:[1,自动冻结] [2,手动冻结]';
COMMENT ON COLUMN sys_user.freeze_start_time IS '冻结开始时间';
COMMENT ON COLUMN sys_user.freeze_end_time IS '冻结结束时间,当前时间在冻结结束区间内,状态为:冻结,3000年默认为:永久冻结';
COMMENT ON COLUMN sys_user.freeze_code IS '冻结原因i18代码';
COMMENT ON COLUMN sys_user.login_time IS '本次登录时间';
COMMENT ON COLUMN sys_user.login_ip IS '本次登录IP';
COMMENT ON COLUMN sys_user.last_active_time IS '最后活跃时间';
COMMENT ON COLUMN sys_user.use_line IS '本次使用线路';
COMMENT ON COLUMN sys_user.last_login_time IS '上次登录时间';
COMMENT ON COLUMN sys_user.last_login_ip IS '上次登录IP';
COMMENT ON COLUMN sys_user.total_online_time IS '累计在线时长';
COMMENT ON COLUMN sys_user.nickname IS '昵称';
COMMENT ON COLUMN sys_user.real_name IS '真实姓名';
COMMENT ON COLUMN sys_user.birthday IS '生日';
COMMENT ON COLUMN sys_user.sex IS '性别，字典类型sex(common模块)';
COMMENT ON COLUMN sys_user.constellation IS '星座';
COMMENT ON COLUMN sys_user.country IS '国家，字典类型country(common模块)';
COMMENT ON COLUMN sys_user.nation IS '民族，字典类型nation(common模块)';
COMMENT ON COLUMN sys_user.register_ip IS '注册ip';
COMMENT ON COLUMN sys_user.avatar_url IS '头像地址';
COMMENT ON COLUMN sys_user.permission_pwd IS '权限密码';
COMMENT ON COLUMN sys_user.idcard IS '身份证号';
COMMENT ON COLUMN sys_user.default_currency IS '默认币种代码，字典类型currency(common模块)';
COMMENT ON COLUMN sys_user.register_site IS '注册网站地址';
COMMENT ON COLUMN sys_user.region IS '省/地区，字典类型province(common模块)';
COMMENT ON COLUMN sys_user.city IS '城市';
COMMENT ON COLUMN sys_user.memo IS '备注';
COMMENT ON COLUMN sys_user.password_level IS '密码级别:[30,高], [20,中] [10,低]';
COMMENT ON COLUMN sys_user.login_ip_dict_code IS '登录IP地区字典代码';
COMMENT ON COLUMN sys_user.last_login_ip_dict_code IS '上次登录IP地区字典代码';
COMMENT ON COLUMN sys_user.register_ip_dict_code IS '注册IP地区字典代码';
COMMENT ON COLUMN sys_user.login_error_times IS '登录错误次数';
COMMENT ON COLUMN sys_user.freeze_title IS '账号冻结标题';
COMMENT ON COLUMN sys_user.freeze_content IS '账号冻结内容';
COMMENT ON COLUMN sys_user.last_logout_time IS '上次退出时间';
COMMENT ON COLUMN sys_user.freeze_user IS '冻结操作人id';
COMMENT ON COLUMN sys_user.disabled_user IS '被停用操作人id';
COMMENT ON COLUMN sys_user.disabled_time IS '被停用时间';
COMMENT ON COLUMN sys_user.freeze_time IS '冻结操作时间';