--更新pt的数据
update game_api_provider set ext_json='{"merchantname":"dawooprod","merchantcode":"QXk2MRtViePbJQSS8YCg781QU5yLDmgr","loginurl":"http://ampinplayopt0matrix.com/api/pt/login.html?key={0}","setNum":"500","search-minute":"10","pre_minute":"0","pre_modify_minute":"5"}' where id=6;
update game_api_interface set api_action='report/getbetlog/startdate/{0}/enddate/{1}/page/{2}/producttype/{3}/currency/{4}' where id=166;
update game_api_interface set http_method='GET' where id=166;
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('550', 'currency', 'currency', 't', NULL, NULL, '', '', '166', '', 'PT-币种', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('551', 'producttype', 'producttype', 't', NULL, NULL, '', '0', '166', '', 'PT-产品类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('552', 'page', 'page', 't', NULL, NULL, '', '1', '166', '', 'PT-玩家', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('553', 'enddate', 'endTime', 't', NULL, NULL, '', '', '166', '', 'PT-查询结束时间', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('554', 'startdate', 'startTime', 't', NULL, NULL, '', '', '166', '', 'PT-查询开始时间', '', '');
