-- auto gen by admin 2016-04-10 21:05:38
TRUNCATE TABLE task_schedule;

--全站任务
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('1', '统计任务-游戏概况', NULL, NULL, 'so.wwb.gamebox.service.stat.GameSurveyProcedureJob', 'execute', 't', '1', '0 0 1 * * ?', 't', '全站任务', '2016-02-21 09:49:05.045', NULL, 'all-001', 'f', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('2', '统计任务-运营概况', NULL, NULL, 'so.wwb.gamebox.service.stat.OperationProfileProcedureJob', 'execute', 't', '1', '0 0 2 * * ?', 't', '全站任务', '2016-02-21 10:07:04.153', NULL, 'all-002', 'f', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('3', '统计任务-收集站点信息', NULL, NULL, 'so.wwb.gamebox.service.stat.SiteInformationProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '全站任务', '2016-01-22 03:11:26.925', NULL, 'all-003', 'f', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('4', '统计任务-运营报表', NULL, NULL, 'so.wwb.gamebox.service.company.ProcedureJob', 'execute', 't', '1', '0 */1 * * * ? 2020', 't', '全站任务', '2015-11-02 16:51:16', NULL, 'all-004', 't', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('99999', '定期删除过期任务-每月一次', NULL, NULL, 'so.wwb.gamebox.service.boss.taskschedule.TaskScheduleService', 'deleteExpireTask', 't', '1', '0 0 0 1 * ?', 't', '全站任务', '2016-02-21 10:07:04.153', NULL, 'all-005', 't', 'f', NULL, NULL);

--api 任务
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('5', 'apiId-1-ds-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-01-15 10:09:31.412', NULL, 'api-1-I', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('6', 'apiId-1-ds-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, 'api-1-M', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('7', 'apiId-2-kg-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-01-15 10:09:31.412', NULL, 'api-2-I', 'f', 'f', '2', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('8', 'apiId-2-kg-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, 'api-2-M', 'f', 'f', '2', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('9', 'apiId-3-mg-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-02-16 03:39:43.778', NULL, 'api-3-I', 'f', 'f', '3', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('10', 'apiId-3-mg-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, 'api-3-M', 'f', 'f', '3', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('11', 'apiId-4-im-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-01-15 10:09:31.412', NULL, 'api-4-I', 'f', 'f', '4', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('12', 'apiId-4-im-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, 'api-4-M', 'f', 'f', '4', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('13', 'apiId-5-gd-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-02-16 03:39:12.429', NULL, 'api-5-I', 'f', 'f', '5', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('14', 'apiId-5-gd-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-02-16 03:33:05.934', NULL, 'api-5-M', 'f', 'f', '5', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('15', 'apiId-6-pt-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-01-15 10:09:31.412', NULL, 'api-6-I', 'f', 'f', '6', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('16', 'apiId-6-pt-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, 'api-6-M', 'f', 'f', '6', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('17', 'apiId-7-og-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-01-15 10:09:31.412', NULL, 'api-7-I', 'f', 'f', '7', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('18', 'apiId-7-og-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, 'api-7-M', 'f', 'f', '7', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('19', 'apiId-8-slc-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-01-15 10:09:31.412', NULL, 'api-8-I', 'f', 'f', '8', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('20', 'apiId-8-slc-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, 'api-8-M', 'f', 'f', '8', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('21', 'apiId-9-ag-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/10 * * * ?', 't', 'api任务', '2016-01-15 10:09:31.412', NULL, 'api-9-I', 'f', 'f', '9', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('22', 'apiId-9-ag-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, 'api-9-M', 'f', 'f', '9', 'java.lang.Integer');

--一次性任务
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('23', '负数余额归零－api转账任务', NULL, NULL, 'so.wwb.gamebox.iservice.master.fund.IPlayerTransferService', 'negative', 'f', '1', '* * * * * ? 2020', 't', '一次性任务', '2016-02-26 06:12:32.567', NULL, 'once-001', 't', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('24', '回收资金', NULL, NULL, 'so.wwb.gamebox.iservice.master.fund.IPlayerTransferService', 'recoveryMoney', 'f', '1', '* * * * * ? 2020', 't', '一次性任务', '2016-01-21 06:32:43.648', NULL, 'once-002', 'f', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('25', '列表数据导出', NULL, NULL, 'so.wwb.gamebox.service.export.ExportJob', 'excuteExport', 't', '1', '* * * * * ? 2020', 't', '一次性任务', '2015-08-04 20:06:16', NULL, 'once-003', 't', 'f', NULL, NULL);

--站点任务
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('26', 'siteId-1-返水未出账单任务', NULL, NULL, 'so.wwb.gamebox.service.master.RebateNotSettledProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-02-16 05:55:16.212', NULL, 'site-1-001', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('27', 'siteId-1-返水账单任务', NULL, NULL, 'so.wwb.gamebox.service.master.RakebakeProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-02-16 05:54:01.465', NULL, 'site-1-002', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('28', 'siteId-1-返佣未出账单任务', NULL, NULL, 'so.wwb.gamebox.service.master.RebateNotSettledProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-02-16 05:52:18.11', NULL, 'site-1-003', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('29', 'siteId-1-返佣周期任务', NULL, NULL, 'so.wwb.gamebox.service.master.RebateProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-01-06 08:27:38.887', NULL, 'site-1-004', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('30', 'siteId-1-回收异常资金任务', NULL, NULL, 'so.wwb.gamebox.service.master.RecoveryAbnormalApiJob', 'execute', 't', '1', '0 0 0/1 * * ?', 't', '站点任务', '2016-01-21 06:22:29.225', NULL, 'site-1-005', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('31', 'siteId-1-推荐奖励周期任务', NULL, NULL, 'so.wwb.gamebox.service.master.PlayerRecommendAwardJob', 'execute', 't', '1', '0 0 0 * * ?', 't', '站点任务', '2016-01-06 04:02:19.205', NULL, 'site-1-006', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('32', 'siteId-1-线上支付超时订单处理任务', NULL, NULL, 'so.wwb.gamebox.service.master.OnlineRechargeJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', '站点任务', '2016-01-21 06:17:19.381', NULL, 'site-1-007', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('33', 'siteId-1-优惠周期任务', NULL, NULL, 'so.wwb.gamebox.service.master.PreferentialProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-01-05 02:57:13.757', NULL, 'site-1-008', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('34', 'siteId-1-站长站点账务(结算)账单.', NULL, NULL, 'so.wwb.gamebox.service.master.StationBillProcedureJob', 'execute', 't', '1', '0 0 0 3 * ?', 't', '站点任务', '2016-01-26 06:01:22.758', NULL, 'site-1-009', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('35', 'siteId-1-站点收款账户清零任务', NULL, NULL, 'so.wwb.gamebox.service.master.AccountClearJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-01-29 05:47:05.688', NULL, 'site-1-010', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('36', 'siteId-1-站点总代账务(结算)账单.', NULL, NULL, 'so.wwb.gamebox.service.master.TopAgentBillProcedureJob', 'execute', 't', '1', '0 0 0 3 * ?', 't', '站点任务', '2016-01-26 06:03:39.534', NULL, 'site-1-011', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('37', 'siteId-1-转账超时订单处理任务', NULL, NULL, 'so.wwb.gamebox.service.master.TransferJob', 'execute', 't', '1', '0 0/15 * * * ?', 't', '站点任务', '2016-01-21 06:20:06.868', NULL, 'site-1-012', 'f', 'f', '1', 'java.lang.Integer');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg", "job_method_arg_class") VALUES ('38', 'siteId-1-返水api基础数据任务', NULL, NULL, 'so.wwb.gamebox.service.master.RakebackApiBaseProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-03-10 03:45:43.691', NULL, 'site-1-013', 'f', 'f', '1', 'java.lang.Integer');
