-- auto gen by cherry 2016-03-11 19:57:25
alter TABLE task_schedule DROP COLUMN IF EXISTS job_method_arg;

 select redo_sqls($$
        ALTER TABLE "task_schedule" add COLUMN "job_method_arg"   text COLLATE "default";
				ALTER TABLE "task_schedule" ADD COLUMN "job_method_arg_class" varchar(100);
  $$);

DELETE FROM qrtz_calendars;
DELETE FROM qrtz_cron_triggers;
DELETE FROM qrtz_fired_triggers;
DELETE FROM qrtz_locks;
DELETE FROM qrtz_paused_trigger_grps;
DELETE FROM qrtz_scheduler_state;
DELETE FROM qrtz_simple_triggers;
DELETE FROM qrtz_simprop_triggers;
DELETE FROM qrtz_triggers;
DELETE FROM qrtz_job_details;
DELETE FROM qrtz_blob_triggers;
DELETE FROM task_run_record;

TRUNCATE TABLE task_schedule;

INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "job_method_arg", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class")
SELECT '99999', '定期删除过期任务-每月一次', NULL, NULL, 'so.wwb.gamebox.service.boss.taskschedule.TaskScheduleService', 'deleteExpireTask', NULL, 't', '1', '0 0 0 1 * ?', 't', '全站任务', '2016-02-21 10:07:04.153', NULL, 'all-005', 't', 'f', NULL
WHERE '99999' not in (SELECT id FROM task_schedule WHERE id='99999');

INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('156', 'apiId-1-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/30 * * * ?', 't', 'api任务', '2016-01-15 10:09:31.412', NULL, '022af9120fb3409d916bbe55b6802506', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('157', 'apiId-1-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/50 * * * ?', 't', 'api任务', '2016-01-15 10:11:59.123', NULL, '062ebf176cb84d7cbbfc9d0b408041d4', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('171', 'apiId-5-gd-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/30 * * * ?', 't', 'api任务', '2016-02-16 03:39:12.429', NULL, '06dc8af6-a0ed-49b1-88b2-850d7223c374', 'f', 'f', 'java.lang.Integer', '5');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('205', '统计任务-游戏概况', NULL, NULL, 'so.wwb.gamebox.service.stat.GameSurveyProcedureJob', 'execute', 't', '1', '0 0 1 * * ?', 't', '全站任务', '2016-02-21 09:49:05.045', NULL, 'all-001', 'f', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('180', '统计任务-运营概况', NULL, NULL, 'so.wwb.gamebox.service.stat.OperationProfileProcedureJob', 'execute', 't', '1', '0 0 2 * * ?', 't', '全站任务', '2016-02-21 10:07:04.153', NULL, 'all-002', 'f', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('162', '统计任务-收集站点信息', NULL, NULL, 'so.wwb.gamebox.service.stat.SiteInformationProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '全站任务', '2016-01-22 03:11:26.925', NULL, 'all-003', 'f', 'f', NULL, NULL);
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('1', '统计任务-运营报表', NULL, NULL, 'so.wwb.gamebox.service.company.ProcedureJob', 'execute', 't', '1', '0 */1 * * * ? 2020', 'f', '全站任务', '2015-11-02 16:51:16', NULL, 'all-004', 't', 'f', NULL, NULL);
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('172', 'apiId-3-gd-下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderFetchJob', 'execute', 't', '1', '0 0/30 * * * ?', 't', 'api任务', '2016-02-16 03:39:43.778', NULL, 'b6a7ffc9-2b8e-426c-a663-2aea1df7c396', 'f', 'f', 'java.lang.Integer', '3');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('170', 'apiId-5-gd-修改下单记录', NULL, NULL, 'so.wwb.gamebox.service.company.PlayerGameOrderModifierJob', 'execute', 't', '1', '0 0/50 * * * ?', 't', 'api任务', '2016-02-16 03:33:05.934', NULL, 'fc55b64e-fdd6-4f86-a04d-957a9a644c3a', 'f', 'f', 'java.lang.Integer', '5');
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('181', '负数余额归零－api转账任务', NULL, NULL, 'so.wwb.gamebox.iservice.master.fund.IPlayerTransferService', 'negative', 'f', '1', '* * * * * ? 2020', 't', '一次性任务', '2016-02-26 06:12:32.567', NULL, 'once-001', 't', 'f', NULL, NULL);
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('161', '回收资金', NULL, NULL, 'so.wwb.gamebox.iservice.master.fund.IPlayerTransferService', 'recoveryMoney', 'f', '1', '* * * * * ? 2020', 'f', '一次性任务', '2016-01-21 06:32:43.648', NULL, 'once-002', 'f', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('777', '列表数据导出', NULL, NULL, 'so.wwb.gamebox.service.export.ExportJob', 'excuteExport', 't', '1', '* * * * * ? 2020', 'f', '一次性任务', '2015-08-04 20:06:16', NULL, 'once-003', 't', 'f', NULL, NULL);
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('189', 'siteId-1-返水未出账单任务', NULL, NULL, 'so.wwb.gamebox.service.master.RebateNotSettledProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-02-16 05:55:16.212', NULL, 'site-1-001', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('190', 'siteId-1-返水账单任务', NULL, NULL, 'so.wwb.gamebox.service.master.RakebakeProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-02-16 05:54:01.465', NULL, 'site-1-002', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('191', 'siteId-1-返佣未出账单任务', NULL, NULL, 'so.wwb.gamebox.service.master.RebateNotSettledProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-02-16 05:52:18.11', NULL, 'site-1-003', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('192', 'siteId-1-返佣周期任务', NULL, NULL, 'so.wwb.gamebox.service.master.RebateProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-01-06 08:27:38.887', NULL, 'site-1-004', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('193', 'siteId-1-回收异常资金任务', NULL, NULL, 'so.wwb.gamebox.service.master.RecoveryAbnormalApiJob', 'execute', 't', '1', '0 0 0/1 * * ?', 't', '站点任务', '2016-01-21 06:22:29.225', NULL, 'site-1-005', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('194', 'siteId-1-推荐奖励周期任务', NULL, NULL, 'so.wwb.gamebox.service.master.PlayerRecommendAwardJob', 'execute', 't', '1', '0 0 0 * * ?', 't', '站点任务', '2016-01-06 04:02:19.205', NULL, 'site-1-006', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('195', 'siteId-1-线上支付超时订单处理任务', NULL, NULL, 'so.wwb.gamebox.service.master.OnlineRechargeJob', 'execute', 't', '1', '0 0 0/5 * * ?', 't', '站点任务', '2016-01-21 06:17:19.381', NULL, 'site-1-007', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('196', 'siteId-1-优惠周期任务', NULL, NULL, 'so.wwb.gamebox.service.master.PreferentialProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-01-05 02:57:13.757', NULL, 'site-1-008', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('197', 'siteId-1-站长站点账务(结算)账单.', NULL, NULL, 'so.wwb.gamebox.service.master.StationBillProcedureJob', 'execute', 't', '1', '0 0 0 3 * ?', 't', '站点任务', '2016-01-26 06:01:22.758', NULL, 'site-1-009', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('198', 'siteId-1-站点收款账户清零任务', NULL, NULL, 'so.wwb.gamebox.service.master.AccountClearJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-01-29 05:47:05.688', NULL, 'site-1-010', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('199', 'siteId-1-站点总代账务(结算)账单.', NULL, NULL, 'so.wwb.gamebox.service.master.TopAgentBillProcedureJob', 'execute', 't', '1', '0 0 0 3 * ?', 't', '站点任务', '2016-01-26 06:03:39.534', NULL, 'site-1-011', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('200', 'siteId-1-转账超时订单处理任务', NULL, NULL, 'so.wwb.gamebox.service.master.TransferJob', 'execute', 't', '1', '0 0 0/1 * * ?', 't', '站点任务', '2016-01-21 06:20:06.868', NULL, 'site-1-012', 'f', 'f', 'java.lang.Integer', '1');
INSERT INTO  "task_schedule" ("id", "job_name", "alias_name", "job_group", "job_class", "job_method", "is_local", "status", "cronexpression", "is_sync", "description", "create_time", "update_time", "job_code", "is_system", "is_dynamic", "job_method_arg_class", "job_method_arg") VALUES ('188', 'siteId-1-返水api基础数据任务', NULL, NULL, 'so.wwb.gamebox.service.master.RakebackApiBaseProcedureJob', 'execute', 't', '1', '0 0 5 * * ?', 't', '站点任务', '2016-03-10 03:45:43.691', NULL, 'site-1-013', 'f', 'f', 'java.lang.Integer', '1');


