-- auto gen by jerry 2016-09-12 09:18:29
INSERT INTO game_api_provider ("id", "abbr_name", "full_name", "api_url", "remarks", "jar_url", "api_class", "jar_version", "ext_json", "default_timezone") SELECT '16', 'EBET', '', 'http://3rd.game.api.com/ebet-api/api/', '测试环境', 'file:/data/impl-jars/api/api-ebet.jar', 'so.wwb.gamebox.service.gameapi.impl.EbetGameApi', '20160910010954', '{"channelId":"139","pageDomain":"http://h5.live888.info","validateTokenExpire":1000000,"search-minute":"10","isDebug":"false","privateKey":"MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAM8OaBwYn4Y3/lJxPEFiSH9O+saF+sFgs5qazPMuJXGtWkXYjAJXf0XlTrOSVkeJkVgQkeBgXeFlXnuZCTR4qsDGHVCy1EmGhYeZKPRrDjoDcpXzwmVGNp8Od7l2GVwSySt8mWGq9OVSBP1Cyin55nFk+YAyKNK9AEvSpIwG4cJzAgMBAAECgYAivZQSQr9hUbvGMWGextLLKYFCFfDAyWzZH+gLVU7LB/8BgRfcvLmKDLNrxb3cOuS8Feuj7gdSbiOwMTkuKKDdch1BYSIBQrPTpf53MuAle/of4tP19kJ66joQ3H2pniBuW/zMnHSKCaA5zZ9Tj2i9MpmiFb/1BotQJQdjHf8oIQJBAOgWIpCPRqr26/qb12U3ON3ciyMQ9mCdJmQ6mL/rRpD6iv27NStSn/C3ao2LYEQctVlDfaNObuqLNOLlVbqwse0CQQDkZAmSx1SC+FfIOM7ES5ab9PCIJwgJEdq1e+pEankP9gHk88PMEAHQcPlJ2Jo+9C9xVlray5yR6f3gw8WVnTnfAkBYBc0mNrD+tpfZfLG82azfuH2s1woaqn+dE/xLDdi9s8hzY0VPIQ84JNhsxqfELX86U7aa8Wxv2Ew+oexZ2hohAkAo5+n3ChCO7J/8UoBmFAvDnxk9qY/839/GRY1t94v7Wdp5AVf+Qpewl6tumIb345Bjwk2/hlxingBEs4u+Ak0NAkB6/e+R9BI8t6sY3AwEaxzb2MIXz9PHUJKBim5HfHuQ+CrboSX8MyZlY5+Wddk8yJQ+ZRrErpL3om+hgbLNW7qx"}', 'GMT+8'  WHERE  not EXISTS (SELECT id from game_api_provider where id='16');


INSERT INTO game_api_interface ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") SELECT '91', 'HTTP', 'rechargestatus', 'checkTransfer', 'POST', 'EBET-验证存取款交易号是否已经处理', 'org.soul.model.gameapi.param.CheckTransferParam', 'org.soul.model.gameapi.result.CheckTransferResult', 'FORM', 'JSON', '16', ''   WHERE  not EXISTS (SELECT id from game_api_interface where id='91');
INSERT INTO game_api_interface ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") SELECT '89', 'HTTP', 'userbethistory', 'fetchRecord', 'POST', 'EBET-获取游戏平台注单', 'org.soul.model.gameapi.param.FetchRecordParam', 'org.soul.model.gameapi.result.FetchRecordResult', 'FORM', 'JSON', '16', ''   WHERE  not EXISTS (SELECT id from game_api_interface where id='89');
INSERT INTO game_api_interface ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") SELECT '88', 'HTTP', 'getusermoney', 'fetchBalance', 'POST', 'EBET-获取游戏平台即时余额', 'org.soul.model.gameapi.param.FetchBalanceParam', 'org.soul.model.gameapi.result.FetchBalanceResult', 'FORM', 'JSON', '16', ''   WHERE  not EXISTS (SELECT id from game_api_interface where id='88');
INSERT INTO game_api_interface ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") SELECT '87', 'HTTP', 'recharge', 'withdraw', 'POST', 'EBET-从游戏平台取款', 'org.soul.model.gameapi.param.WithdrawParam', 'org.soul.model.gameapi.result.WithdrawResult', 'FORM', 'JSON', '16', ''   WHERE  not EXISTS (SELECT id from game_api_interface where id='87');
INSERT INTO game_api_interface ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") SELECT '86', 'HTTP', 'LOGIN', 'login', 'POST', 'EBET-登录到游戏平台', 'org.soul.model.gameapi.param.LoginParam', 'org.soul.model.gameapi.result.LoginResult', 'FORM', 'JSON', '16', ''   WHERE  not EXISTS (SELECT id from game_api_interface where id='86');
INSERT INTO game_api_interface ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") SELECT '85', 'HTTP', 'recharge', 'deposit', 'POST', 'EBET-转账到游戏平台', 'org.soul.model.gameapi.param.DepositParam', 'org.soul.model.gameapi.result.DepositResult', 'FORM', 'JSON', '16', ''   WHERE  not EXISTS (SELECT id from game_api_interface where id='85');
INSERT INTO game_api_interface ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") SELECT '84', 'HTTP', 'syncuser', 'register', 'POST', 'EBET-创建账号', 'org.soul.model.gameapi.param.RegisterParam', 'org.soul.model.gameapi.result.RegisterResult', 'FORM', 'JSON', '16', ''   WHERE  not EXISTS (SELECT id from game_api_interface where id='84');




INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '147', 'username', 'user.account', 't', NULL, NULL, '^[0-9a-zA-Z]{1,20}$', NULL, '84', NULL, 'EBET-玩家在游戏平台的帐号', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='147');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '148', 'channelId', 'channelId', 't', NULL, NULL, '', NULL, '84', NULL, 'EBET-渠道 ID', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='148');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '154', 'signature', 'signature', 't', NULL, NULL, '', NULL, '84', NULL, 'EBET-签名(字符串拼接) username', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='154');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '149', 'lang', 'lang', 't', NULL, NULL, '', NULL, '84', NULL, 'EBET-语言', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='149');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1602', 'money', 'amount', 't', NULL, NULL, NULL, NULL, '85', NULL, 'EBET-存款金额', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1602');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1604', 'timestamp', 'timestamp', 't', NULL, NULL, NULL, NULL, '85', NULL, 'EBET-当前时间(', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1604');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1605', 'signature', 'signature', 't', NULL, NULL, NULL, NULL, '85', NULL, 'EBET-签名', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1605');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1603', 'rechargeReqId', 'transId', 't', NULL, NULL, NULL, NULL, '85', NULL, 'EBET-存款标示（检查存款状态）', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1603');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1606', 'channelId', 'channelId', 't', NULL, NULL, NULL, NULL, '85', NULL, 'EBET-渠道id', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1606');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1610', 'channelId', 'channelId', 't', NULL, NULL, NULL, NULL, '91', NULL, 'EBET-渠道id', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1610');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1611', 'signature', 'signature', 't', NULL, NULL, NULL, NULL, '91', NULL, 'EBET-签名', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1611');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1612', 'rechargeReqId', 'transId', 't', NULL, NULL, NULL, NULL, '91', NULL, 'EBET-存款标示（检查存款状态）', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1612');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1631', 'startTimeStr', 'startTimeStr', 'f', NULL, NULL, NULL, NULL, '89', NULL, 'EBET-开始时间', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1631');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1632', 'endTimeStr', 'endTimeStr', 'f', NULL, NULL, NULL, NULL, '89', NULL, 'EBET-结束时间', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1632');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1633', 'channelId', 'channelId', 't', NULL, NULL, NULL, NULL, '89', NULL, 'EBET-渠道id', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1633');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1634', 'subChannelId', 'subChannelId', 'f', NULL, NULL, NULL, NULL, '89', NULL, 'EBET-子渠道id', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1634');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1637', 'timestamp', 'timestamp', 't', NULL, NULL, NULL, NULL, '89', NULL, 'EBET-当前时间 ( Unix time )', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1637');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1638', 'signature', 'signature', 't', NULL, NULL, NULL, NULL, '89', NULL, 'EBET-签名 (字符串拼
接) username+timestamp', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1638');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1636', 'pageSize', 'pageSize', 'f', NULL, NULL, NULL, NULL, '89', NULL, 'EBET-每页数量。(最多上限 100 )
如不设置,自定义为 100', '1', '100'   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1636');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1635', 'pageNum', 'pageNum', 'f', NULL, NULL, NULL, NULL, '89', NULL, 'EBET-页码 ,如不设置,自定义为 1', '1', NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1635');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1642', 'signature', 'signature', 't', NULL, NULL, NULL, NULL, '88', NULL, 'EBET-签名 (字符串拼
接) username', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1642');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1643', 'channelId', 'channelId', 't', NULL, NULL, NULL, NULL, '88', NULL, 'EBET-渠道id', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1643');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1651', 'channelId', 'channelId', 't', NULL, NULL, NULL, NULL, '87', NULL, 'EBET-渠道id', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1651');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1652', 'signature', 'signature', 't', NULL, NULL, NULL, NULL, '87', NULL, 'EBET-签名', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1652');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1653', 'timestamp', 'timestamp', 't', NULL, NULL, NULL, NULL, '87', NULL, 'EBET-当前时间(', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1653');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1654', 'rechargeReqId', 'transId', 't', NULL, NULL, NULL, NULL, '87', NULL, 'EBET-存款标示（检查存款状态）', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1654');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1655', 'money', 'amount', 't', NULL, NULL, NULL, NULL, '87', NULL, 'EBET-存款金额', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1655');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1601', 'username', 'user.account', 't', NULL, NULL, '^[0-9a-zA-Z]{1,20}$', NULL, '85', NULL, 'EBET-玩家账号', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1601');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1620', 'username', 'user.account', 't', NULL, NULL, '^[0-9a-zA-Z]{1,20}$', NULL, '86', NULL, 'EBET-玩家账号', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1620');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1630', 'username', 'username', 'f', NULL, NULL, '^[0-9a-zA-Z]{1,20}$', NULL, '89', NULL, 'EBET-用户名', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1630');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1641', 'username', 'username', 't', NULL, NULL, '^[0-9a-zA-Z]{1,20}$', NULL, '88', NULL, 'EBET-批量查询用户金额用户', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1641');
INSERT INTO game_api_interface_request ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") SELECT '1656', 'username', 'user.account', 't', NULL, NULL, '^[0-9a-zA-Z]{1,20}$', NULL, '87', NULL, 'EBET-玩家账号', NULL, NULL   WHERE  not EXISTS (SELECT id from game_api_interface_request where id='1656');



UPDATE game_api_provider SET default_timezone='-4' where abbr_name='IM';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='DS';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='EBET';
UPDATE game_api_provider SET default_timezone='+0' where abbr_name='MG';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='KG';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='SLC';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='GD';
UPDATE game_api_provider SET default_timezone='-4' where abbr_name='AG';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='PG';
UPDATE game_api_provider SET default_timezone='-4' where abbr_name='NYX';
UPDATE game_api_provider SET default_timezone='+4' where abbr_name='SS';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='HB';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='SA';
UPDATE game_api_provider SET default_timezone='-4' where abbr_name='BB';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='OG';
UPDATE game_api_provider SET default_timezone='+8' where abbr_name='PT';


UPDATE sys_resource SET name='转账异常对单',remark='转账异常对单',url='apiTransferCheck/exceptionTransfer/index.html' WHERE id=511;