-- auto gen by admin 2016-10-19 17:10:15
--AG的小费接口
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('201', 'HTTP', '', 'tip', 'POST', 'AG-小费订单', 'org.soul.model.gameapi.param.TipParam', 'org.soul.model.gameapi.result.TipRecordResult', 'XML', 'XML', '9', '');

INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('835', 'startTime', 'startTime', 't', NULL, NULL, '', '', '201', '', 'AG-查询开始时间', '', '');
--BB小费接口
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('219', 'HTTP', 'BetRecord', 'tip', 'POST', 'BB-获取小费', 'org.soul.model.gameapi.param.TipParam', 'org.soul.model.gameapi.result.TipRecordResult', 'FORM', 'JSON', '10', '');

INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('952', 'uppername', 'uppername', 't', NULL, NULL, '', '', '219', '', 'BB-玩家游戏账号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('950', 'website', 'website', 't', NULL, NULL, '', '', '219', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('951', 'username', 'username', 'f', NULL, NULL, '', '', '219', '', 'BB-会员帐号(请输 4-20个 , 仅 输 数 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('953', 'key', 'key', 't', NULL, NULL, '', '', '219', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('954', 'rounddate', 'rounddate', 't', NULL, NULL, '', '', '219', '', 'BB-日期', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('955', 'starttime', 'starttime', 'f', NULL, NULL, '', '', '219', '', 'BB-开始时间（bb体育无效）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('956', 'endtime', 'endtime', 'f', NULL, NULL, '', '', '219', '', 'BB-结束时间（bb体育无效）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('957', 'gamekind', 'gamekind', 't', NULL, NULL, '', '', '219', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('958', 'subgamekind', 'subgamekind', 'f', NULL, NULL, '', '', '219', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('959', 'gametype', 'gametype', 'f', NULL, NULL, '', '', '219', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('960', 'pagelimit', 'pagelimit', 'f', NULL, NULL, '', '', '219', '', 'BB-每页数量', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('961', 'page', 'page', 'f', NULL, NULL, '', '', '219', '', 'BB-查询页数', '', '');
