--修改kg
update  game_api_interface set api_action ='player_fund_in_out_first.php' where id='32';
update  game_api_interface set api_action ='player_fund_in_out_first.php' where id='33';
update  game_api_interface_request set required ='f' where id=181;
update  game_api_interface_request set required ='f' where id=177;

update game_api_provider set ext_json ='{"cagent":"H48_AGIN","Encrypt_key":"YDEZF2Nf","MD5_key":"lHNkkp0DX8La","loginurl":"http://gci.ampinplayopt0matrix.com:81/forwardGame.do?params={0}&key={1}","dm":"http://gci.ampinplayopt0matrix.com","search-minute":"16","setNum":"500","ftpHost":"br.agingames.com","ftpPort":"21","ftpUserName":"H48.dayu","ftpPassword":"n3JJXo7eWQ","ftprootPath":"/AGIN/","lostAndfound":"lostAndfound"}'  where id=9;
--新增BB
INSERT INTO "game_api_provider" ("id", "abbr_name", "full_name", "api_url", "remarks", "jar_url", "api_class", "jar_version", "ext_json") VALUES ('10', 'BB', '', 'http://linkapi.bbpicdance.info/app/WebService/JSON/display.php', 'http://3rd.game.api.com/bb-api/app/WebService/JSON/display.php|||||||http://3rd.game.api.com/bb-login-api', 'gamebox-api/api-impl/impl-jars/api-bb.jar', 'so.wwb.gamebox.service.gameapi.impl.BbGameApi', '201604291942', '{"website":"dawoo","uppername":"ddwb001","gameUrl":"http://888.bbpicdance.info/app/WebService/JSON/display.php","setNum":"500","search-minute":"10","modify-minute":"5"}');



--新增BB
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('214', 'HTTP', 'Transfer', 'withdraw', 'GET', 'BB-从游戏平台取款', 'org.soul.model.gameapi.param.WithdrawParam', 'org.soul.model.gameapi.result.WithdrawResult', 'JSON', 'JSON', '10', '{"Transfer":"cI12Fr9"}');
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('218', 'HTTP', 'BetRecordByModifiedDate3', 'fetchModifiedRecord', 'GET', 'BB-获取派彩注单数据', 'org.soul.model.gameapi.param.FetchModifiedRecordParam', 'org.soul.model.gameapi.result.FetchModifiedRecordResult', 'JSON', 'JSON', '10', '{"BetRecordByModifiedDate3":"D2c48m5"}');
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('215', 'HTTP', 'CheckTransfer', 'checkTransfer', 'GET', 'BB-验证存取款交易号是否已经处理', 'org.soul.model.gameapi.param.CheckTransferParam', 'org.soul.model.gameapi.result.CheckTransferResult', 'JSON', 'JSON', '10', '{"CheckTransfer":"8bTqLR"}');
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('217', 'HTTP', 'BetRecord', 'fetchRecord', 'GET', 'BB-获取游戏平台注单', 'org.soul.model.gameapi.param.FetchRecordParam', 'org.soul.model.gameapi.result.FetchRecordResult', 'JSON', 'JSON', '10', '{"BetRecord":"D2c48m5"}');
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('213', 'HTTP', 'Transfer', 'deposit', 'GET', 'BB-转账到游戏平台', 'org.soul.model.gameapi.param.DepositParam', 'org.soul.model.gameapi.result.DepositResult', 'JSON', 'JSON', '10', '{"Transfer":"cI12Fr9"}');
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('211', 'HTTP', 'Login', 'login', 'GET', 'BB-登录游戏', 'org.soul.model.gameapi.param.LoginParam', 'org.soul.model.gameapi.result.LoginResult', 'JSON', 'JSON', '10', '{"Login":"TzgY0wcK"}');
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('210', 'HTTP', 'CreateMember', 'register', 'GET', 'BB-创建账号并登录到游戏平台，', 'org.soul.model.gameapi.param.RegisterParam', 'org.soul.model.gameapi.result.RegisterResult', 'JSON', 'JSON', '10', '{"CreateMember":"Gw7skzgD75"}');
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('212', 'HTTP', 'Logout', 'kickOut', 'GET', 'BB-强制登出', 'org.soul.model.gameapi.param.KickOutParam', 'org.soul.model.gameapi.result.KickOutResult', 'JSON', 'JSON', '10', '{"Logout":"IAUdy562fS"}');
INSERT INTO "game_api_interface" ("id", "protocol", "api_action", "local_action", "http_method", "remarks", "param_class", "result_class", "request_content_type", "response_content_type", "provider_id", "ext_json") VALUES ('216', 'HTTP', 'CheckUsrBalance', 'fetchBalance', 'GET', 'BB-获取游戏平台即时余额', 'org.soul.model.gameapi.param.FetchBalanceParam', 'org.soul.model.gameapi.result.FetchBalanceResult', 'JSON', 'JSON', '10', '{"CheckUsrBalance":"BWspzlPv"}');


--新增BB
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('840', 'website', 'website', 't', NULL, NULL, '', '', '210', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('841', 'username', 'user.account', 't', NULL, NULL, '', '', '210', '', 'BB-会员账号(请输 4-20个 , 仅 输 数 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('843', 'uppername', 'uppername', 't', NULL, NULL, '', '', '210', '', 'BB-玩家游戏账号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('844', 'key', 'key', 't', NULL, NULL, '', '', '210', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('851', 'website', 'website', 't', NULL, NULL, '', '', '211', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('852', 'username', 'user.account', 't', NULL, NULL, '', '', '211', '', 'BB-会员账号(请输 4-20个 , 仅 输 数 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('853', 'uppername', 'uppername', 't', NULL, NULL, '', '', '211', '', 'BB-玩家游戏账号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('855', 'key', 'key', 't', NULL, NULL, '', '', '211', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('856', 'lang', 'user.locale', 't', NULL, NULL, '', '', '211', '', 'BB-玩家的语言', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('857', 'page_site', 'page_site', 'f', NULL, NULL, '', '', '211', '', 'BB ball 视讯 live game Ltlotte 为 则导 页 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('858', 'page_present', 'page_present', 'f', NULL, NULL, '', '', '211', '', 'BB 视讯 live 导 视讯 厅页 时带 page_site ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('849', 'gamecode', 'gameId', 'f', NULL, NULL, '', '', '211', '', 'BBgamekind=3時，需強制帶入', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('850', 'gametype', 'gametype', 'f', NULL, NULL, '', '', '211', '', 'BB5042、5087、5903，目前僅支援app版，web版尚未開放', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('859', 'gamekind', 'gamekind', 'f', NULL, NULL, '', '', '211', '', 'BB遊戲種類(3：視訊、5：機率、15：3D廳)', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('860', 'key', 'key', 't', NULL, NULL, '', '', '212', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('861', 'username', 'user.account', 't', NULL, NULL, '', '', '212', '', 'BB-会员账号(请输 4-20个 , 仅 输 数 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('862', 'website', 'website', 't', NULL, NULL, '', '', '212', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('870', 'website', 'website', 't', NULL, NULL, '', '', '213', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('871', 'username', 'user.account', 't', NULL, NULL, '', '', '213', '', 'BB-会员账号(请输 4-20个 , 仅 输 数 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('873', 'uppername', 'uppername', 't', NULL, NULL, '', '', '213', '', 'BB-玩家游戏账号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('874', 'key', 'key', 't', NULL, NULL, '', '', '213', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('875', 'remitno', 'api_transId', 't', NULL, NULL, '', '', '213', '', 'BB-转账交易号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('876', 'action', 'action', 't', NULL, NULL, '', 'IN', '213', '', 'BB-IN(转入) OUT(转出) ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('877', 'remit', 'amount', 't', NULL, NULL, '', '', '213', '', 'BB-转账金额', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('880', 'website', 'website', 't', NULL, NULL, '', '', '214', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('881', 'username', 'user.account', 't', NULL, NULL, '', '', '214', '', 'BB-会员账号(请输 4-20个 , 仅 输 数 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('883', 'uppername', 'uppername', 't', NULL, NULL, '', '', '214', '', 'BB-玩家游戏账号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('884', 'key', 'key', 't', NULL, NULL, '', '', '214', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('885', 'remitno', 'api_transId', 't', NULL, NULL, '', '', '214', '', 'BB-转账交易号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('886', 'action', 'action', 't', NULL, NULL, '', 'OUT', '214', '', 'BB-IN(转入) OUT(转出) ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('887', 'remit', 'amount', 't', NULL, NULL, '', '', '214', '', 'BB-转账金额', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('890', 'website', 'website', 't', NULL, NULL, '', '', '215', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('891', 'transid', 'api_transId', 't', NULL, NULL, '', '', '215', '', 'BB-转账交易号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('892', 'key', 'key', 't', NULL, NULL, '', '', '215', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('900', 'website', 'website', 't', NULL, NULL, '', '', '216', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('901', 'username', 'username', 't', NULL, NULL, '', '', '216', '', 'BB-会员账号(请输 4-20个 , 仅 输 数 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('902', 'uppername', 'uppername', 't', NULL, NULL, '', '', '216', '', 'BB-玩家游戏账号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('903', 'key', 'key', 't', NULL, NULL, '', '', '216', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('904', 'page', 'page', 'f', NULL, NULL, '', '', '216', '', 'BB-查询页数', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('905', 'pagelimit', 'pagelimit', 'f', NULL, NULL, '', '', '216', '', 'BB-每页数量', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('910', 'website', 'website', 't', NULL, NULL, '', '', '217', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('911', 'username', 'username', 'f', NULL, NULL, '', '', '217', '', 'BB-会员账号(请输 4-20个 , 仅 输 数 ', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('912', 'uppername', 'uppername', 't', NULL, NULL, '', '', '217', '', 'BB-玩家游戏账号', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('913', 'key', 'key', 't', NULL, NULL, '', '', '217', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('914', 'rounddate', 'rounddate', 't', NULL, NULL, '', '', '217', '', 'BB-日期', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('915', 'starttime', 'starttime', 'f', NULL, NULL, '', '', '217', '', 'BB-开始时间（bb体育无效）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('916', 'endtime', 'endtime', 'f', NULL, NULL, '', '', '217', '', 'BB-结束时间（bb体育无效）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('917', 'gamekind', 'gamekind', 't', NULL, NULL, '', '', '217', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('918', 'subgamekind', 'subgamekind', 'f', NULL, NULL, '', '', '217', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('919', 'gametype', 'gametype', 'f', NULL, NULL, '', '', '217', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('920', 'pagelimit', 'pagelimit', 'f', NULL, NULL, '', '', '217', '', 'BB-每页数量', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('921', 'page', 'page', 'f', NULL, NULL, '', '', '217', '', 'BB-查询页数', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('930', 'website', 'website', 't', NULL, NULL, '', '', '218', '', 'BB-网站名称', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('931', 'key', 'key', 't', NULL, NULL, '', '', '218', '', 'BB-验证码（全部小写）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('932', 'starttime', 'starttime', 'f', NULL, NULL, '', '', '218', '', 'BB-开始时间（bb体育无效）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('933', 'endtime', 'endtime', 'f', NULL, NULL, '', '', '218', '', 'BB-结束时间（bb体育无效）', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('934', 'gamekind', 'gamekind', 't', NULL, NULL, '', '', '218', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('935', 'subgamekind', 'subgamekind', 'f', NULL, NULL, '', '', '218', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('936', 'gametype', 'gametype', 'f', NULL, NULL, '', '', '218', '', 'BB-游戏类型', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('937', 'page', 'page', 'f', NULL, NULL, '', '', '218', '', 'BB-查询页数', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('938', 'start_date', 'start_date', 'f', NULL, NULL, '', '', '218', '', 'BB-开始日期', '', '');
INSERT INTO "game_api_interface_request" ("id", "api_field_name", "property_name", "required", "min_length", "max_length", "reg_exp", "default_value", "interface_id", "remarks", "comment", "min_value", "max_value") VALUES ('939', 'end_date', 'end_date', 'f', NULL, NULL, '', '', '218', '', 'BB-结束日期', '', '');





--BB--真实环境
update game_api_provider set api_url ='http://3rd.game.api.com/bb-api/app/WebService/JSON/display.php' where id=10;
update game_api_provider set ext_json ='{"website":"dawoo","uppername":"ddwb001","gameUrl":"http://3rd.game.api.com/bb-login-api/app/WebService/JSON/display.php","setNum":"500","search-minute":"10","modify-minute":"5"}'  where id=10;
update game_api_provider set jar_url='file:/data/impl-jars/api-bb.jar'  where id=10;
--更新所有版本号
update game_api_provider set jar_version=to_char(CURRENT_TIMESTAMP, 'yyyymmddhhmmss');
