-- auto gen by longer 2015-10-27 09:46:42

--Longer 从V1.0.1.0134__A_ctt_material_lorne 转移过来
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '794', 'setting', 'master_question3', '6', '6', '我第一辆车的车牌是？', NULL, 't' WHERE 794 NOT IN(SELECT id FROM sys_dict WHERE id=794);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '793', 'setting', 'master_question3', '5', '5', '我的工号是？', NULL, 't' WHERE 793 NOT IN(SELECT id FROM sys_dict WHERE id=793);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '792', 'setting', 'master_question3', '4', '4', '我高考的总分是？', NULL, 't' WHERE 792 NOT IN(SELECT id FROM sys_dict WHERE id=792);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '791', 'setting', 'master_question3', '3', '3', '我的初恋的名字是？', NULL, 't' WHERE 791 NOT IN(SELECT id FROM sys_dict WHERE id=791);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '790', 'setting', 'master_question3', '2', '2', '我的结婚纪念日是？', NULL, 't' WHERE 790 NOT IN(SELECT id FROM sys_dict WHERE id=790);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '789', 'setting', 'master_question3', '1', '1', '我第一次购房的日期？', NULL, 't' WHERE 789 NOT IN(SELECT id FROM sys_dict WHERE id=789);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '788', 'setting', 'master_question2', '6', '6', '我的幸运数字？', NULL, 't' WHERE 788 NOT IN(SELECT id FROM sys_dict WHERE id=788);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '787', 'setting', 'master_question2', '5', '5', '我向往的旅游地是？', NULL, 't' WHERE 787 NOT IN(SELECT id FROM sys_dict WHERE id=787);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '786', 'setting', 'master_question2', '4', '4', '我最喜欢的一部电影名称是？', NULL, 't' WHERE 786 NOT IN(SELECT id FROM sys_dict WHERE id=786);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '785', 'setting', 'master_question2', '3', '3', '我最喜欢的汽车品牌是？', NULL, 't' WHERE 785 NOT IN(SELECT id FROM sys_dict WHERE id=785);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '784', 'setting', 'master_question2', '2', '2', '我最喜欢的一首歌？', NULL, 't' WHERE 784 NOT IN(SELECT id FROM sys_dict WHERE id=784);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '783', 'setting', 'master_question2', '1', '1', '我比较喜欢的球类运动是？', NULL, 't' WHERE 783 NOT IN(SELECT id FROM sys_dict WHERE id=783);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '782', 'setting', 'master_question1', '12', '12', '我的妹妹的名字是？', NULL, 't' WHERE 782 NOT IN(SELECT id FROM sys_dict WHERE id=782);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '781', 'setting', 'master_question1', '11', '11', '我的弟弟的名字是？', NULL, 't' WHERE 781 NOT IN(SELECT id FROM sys_dict WHERE id=781);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '780', 'setting', 'master_question1', '10', '10', '我的姐姐的名字是？', NULL, 't' WHERE 780 NOT IN(SELECT id FROM sys_dict WHERE id=780);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '779', 'setting', 'master_question1', '9', '9', '我的哥哥的名字是？', NULL, 't' WHERE 779 NOT IN(SELECT id FROM sys_dict WHERE id=779);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '778', 'setting', 'master_question1', '8', '8', '我的孩子的名字是？', NULL, 't' WHERE 778 NOT IN(SELECT id FROM sys_dict WHERE id=778);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '777', 'setting', 'master_question1', '7', '7', '我的爱人的名字是？', NULL, 't' WHERE 777 NOT IN(SELECT id FROM sys_dict WHERE id=777);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '776', 'setting', 'master_question1', '6', '6', '我的妈妈的名字是？', NULL, 't' WHERE 776 NOT IN(SELECT id FROM sys_dict WHERE id=776);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '775', 'setting', 'master_question1', '5', '5', '我的爸爸的名字是？', NULL, 't' WHERE 775 NOT IN(SELECT id FROM sys_dict WHERE id=775);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '774', 'setting', 'master_question1', '4', '4', '我的外婆的名字是？', NULL, 't' WHERE 774 NOT IN(SELECT id FROM sys_dict WHERE id=774);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '773', 'setting', 'master_question1', '3', '3', '我的外公的名字是？', NULL, 't' WHERE 773 NOT IN(SELECT id FROM sys_dict WHERE id=773);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '772', 'setting', 'master_question1', '2', '2', '我的奶奶的名字是？', NULL, 't' WHERE 772 NOT IN(SELECT id FROM sys_dict WHERE id=772);
INSERT INTO "sys_dict" ("id", "module", "dict_type", "dict_code", "order_num", "remark", "parent_code", "active") SELECT '771', 'setting', 'master_question1', '1', '1', '我的爷爷的名字是？', NULL, 't' WHERE 771 NOT IN(SELECT id FROM sys_dict WHERE id=771);