DROP FUNCTION IF EXISTS gamebox_collect_site_infor(text);
DROP FUNCTION IF EXISTS gamebox_game_survey(text, int, text);
DROP FUNCTION IF EXISTS gamebox_generate_order_no(text, text, text);
DROP FUNCTION IF EXISTS gamebox_generate_order_no(text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_operation_company(text);
DROP FUNCTION IF EXISTS gamebox_operation_favorable_calculate(hstore, float);
DROP FUNCTION IF EXISTS gamebox_operation_master(text);
DROP FUNCTION IF EXISTS gamebox_operation_occupy_api(text, text, text);
DROP FUNCTION IF EXISTS gamebox_operation_occupy_calculate(FLOAT[], FLOAT[], FLOAT, BOOLEAN);
DROP FUNCTION IF EXISTS gamebox_operation_occupy_to_array(text, int);
DROP FUNCTION IF EXISTS gamebox_operation_profile(text, int, text);
DROP FUNCTION IF EXISTS gamebox_operation_site(text, date);
DROP FUNCTION IF EXISTS gamebox_operations_statement(text, text[], text[], text[], text[]);
DROP FUNCTION IF EXISTS gamebox_operations_statement(text, text, text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_role_information(text);
DROP FUNCTION IF EXISTS gamebox_site_information(text);
DROP FUNCTION IF EXISTS gamebox_site_information(text, text, text);
DROP FUNCTION IF EXISTS gamebox_site_map(int);
DROP FUNCTION IF EXISTS gamebox_site_rakeback(text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_site_rakeback(text, text, timestamp, timestamp);
DROP FUNCTION IF EXISTS gamebox_site_rakeback(text, text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_site_rakeback_api(hstore);
DROP FUNCTION IF EXISTS gamebox_site_rakeback_gametype(hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_site_rakeback_player(hstore);
DROP FUNCTION IF EXISTS gamebox_site_rebate(hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_site_rebate(text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_site_rebate(text, text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_site_rebate_api(hstore);
DROP FUNCTION IF EXISTS gamebox_site_rebate_gametype(hstore, hstore);
DROP FUNCTION IF EXISTS gamebox_station_bill(hstore);
DROP FUNCTION IF EXISTS gamebox_station_bill(text, text, text, text, int);
DROP FUNCTION IF EXISTS gamebox_station_bill(text, text, text, text, text, int);
DROP FUNCTION IF EXISTS gamebox_station_bill_master(hstore, hstore, text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_station_bill_other(hstore, hstore, int);
DROP FUNCTION IF EXISTS gamebox_station_bill_other(hstore);
DROP FUNCTION if exists gamebox_station_bill_prev(INT, INT, INT, TEXT);
DROP FUNCTION IF EXISTS gamebox_station_bill_top(hstore, hstore, text, text, text, text);
DROP FUNCTION IF EXISTS gamebox_station_no_bill(int, int, int, text);
DROP FUNCTION IF EXISTS gamebox_station_profit_loss(hstore);