-- auto gen by cherry 2017-04-24 19:53:39
DROP VIEW if EXISTS v_player_deposit;
CREATE OR REPLACE VIEW "v_player_deposit" AS
 SELECT a.id,
    a.player_id,
    a.username,
    a.rank_id,
    a.create_time,
    a.recharge_type,
    a.is_first_recharge,
    a.payer_bank,
    a.payer_bankcard,
    a.bank_order,
    a.recharge_address,
    a.pay_account_id,
    a.bank_code,
    a.full_name,
    a.counter_fee,
    a.default_currency,
    a.recharge_amount,
    a.recharge_total_amount,
    a.check_status,
    a.recharge_status,
    a.check_user_id,
    a.check_username,
    a.check_time,
    a.payer_name,
    a.transaction_no,
    a.custom_bank_name,
    a.account,
    a.recharge_type_parent,
    a.check_remark,
    a.failure_title,
    a.pay_account_status,
    a.deposit_count,
    a.recharge_count,
    a.ip_deposit,
    a.ip_dict_code,
    a.pay_url,
    a.origin,
    a.pay_name,
    ra.rank_name,
    ra.risk_marker,
    a.account_type,
    a.channel_json,
    a.favorable_total_amount
   FROM (( SELECT pr.id,
            pr.player_id,
            su.username,
                CASE
                    WHEN (pt.rank_id IS NULL) THEN up.rank_id
                    ELSE pt.rank_id
                END AS rank_id,
            pr.create_time,
            pr.recharge_type,
            pr.is_first_recharge,
            pr.payer_bank,
            pr.payer_bankcard,
            pr.bank_order,
            pr.recharge_address,
            pr.pay_account_id,
            pa.bank_code,
            pa.full_name,
            pr.counter_fee,
            su.default_currency,
            pr.recharge_amount,
            pr.recharge_total_amount,
            pr.check_status,
            pr.recharge_status,
            pr.check_user_id,
            pr.check_username,
            pr.check_time,
            pr.payer_name,
            pr.transaction_no,
            pa.custom_bank_name,
            pa.account,
            pr.recharge_type_parent,
            pr.check_remark,
            pr.failure_title,
            pa.status AS pay_account_status,
            pa.deposit_count,
            up.recharge_count,
            pr.ip_deposit,
            pr.ip_dict_code,
            pr.pay_url,
            pt.origin,
            pa.pay_name,
            pa.account_type,
            pa.channel_json,
            pr.favorable_total_amount
           FROM ((((player_recharge pr
             LEFT JOIN sys_user su ON ((pr.player_id = su.id)))
             LEFT JOIN user_player up ON ((pr.player_id = up.id)))
             LEFT JOIN pay_account pa ON ((pr.pay_account_id = pa.id)))
             LEFT JOIN player_transaction pt ON (((pr.transaction_no)::text = (pt.transaction_no)::text)))) a
     LEFT JOIN player_rank ra ON ((ra.id = a.rank_id)));

COMMENT ON VIEW "v_player_deposit" IS 'Fei - 玩家存款列表视图';