-- auto gen by marz 2017-11-02 23:46:45
--update pro bug
--update lottery_bet_order set status='1' where expect='2017128' and code='hklhc' and payout=0 and status='2' and bet_code in ('lhc_five_no_in','lhc_six_no_in','lhc_seven_no_in','lhc_eight_no_in','lhc_nine_no_in','lhc_ten_no_in','lhc_eleven_no_in','lhc_twelve_no_in');
--select lottery_payout('2017128','hklhc','host=172.17.0.11 port=5432 dbname=gb-companies user=gb-companies password=postgres');