-- auto gen by jerry 2015-10-30 09:36:45
UPDATE "sys_resource" SET "name"='公告栏管理' WHERE ("id"='607');
UPDATE "sys_param" SET param_value='[{"bulitIn":"true","id":1,"sort":1,"name":"regCode","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"true","id":2,"sort":2,"name":"username","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"true","id":3,"sort":3,"name":"password","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"true","id":4,"sort":4,"name":"verificationCode","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"true","id":5,"sort":5,"name":"defaultTimezone","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"false","id":6,"sort":6,"name":"303","isRequired":"1","isRegField":"2","status":"2"},{"bulitIn":"false","id":7,"sort":7,"name":"201","isRequired":"1","isRegField":"2","status":"0"},{"bulitIn":"false","id":8,"sort":8,"name":"countryCity","isRequired":"1","isRegField":"1","status":"0"},{"bulitIn":"false","id":9,"sort":9,"name":"sex","isRequired":"1","isRegField":"1","status":"1"},{"bulitIn":"false","id":10,"sort":10,"name":"nickName","isRequired":"1","isRegField":"1","status":"1"},{"bulitIn":"false","id":11,"sort":11,"name":"defaultLocale","isRequired":"1","isRegField":"2","status":"0"},{"bulitIn":"false","id":12,"sort":12,"name":"302","isRequired":"1","isRegField":"2","status":"2"},{"bulitIn":"false","id":13,"sort":13,"name":"110","isRequired":"1","isRegField":"1","status":"0"},{"bulitIn":"false","id":14,"sort":14,"name":"birthday","isRequired":"1","isRegField":"1","status":"1"},{"bulitIn":"false","id":15,"sort":15,"name":"paymentPassword","isRequired":"1","isRegField":"1","status":"0"},{"bulitIn":"false","id":16,"sort":16,"name":"realName","isRequired":"1","isRegField":"1","status":"0"},{"bulitIn":"false","id":17,"sort":17,"name":"301","isRequired":"1","isRegField":"1","status":"1"},{"bulitIn":"false","id":18,"sort":18,"name":"serviceTerms","isRequired":"1","isRegField":"1","status":"0"},{"bulitIn":"false","id":19,"sort":19,"name":"securityIssues","isRequired":"1","isRegField":"1","status":"0"},{"bulitIn":"false","id":20,"sort":20,"name":"mainCurrency","isRequired":"1","isRegField":"2","status":"0"},{"bulitIn":"false","id":21,"sort":21,"name":"constellation","isRequired":"2","isRegField":"2","status":"0"}]' WHERE id = 73;
UPDATE "sys_param" SET param_value='[{"bulitIn":"true","id":1,"sort":1,"name":"regCode","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"true","id":2,"sort":2,"name":"username","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"true","id":3,"sort":3,"name":"password","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"true","id":4,"sort":4,"name":"verificationCode","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"true","id":5,"sort":5,"name":"defaultTimezone","isRequired":"0","isRegField":"0","status":"0"},{"bulitIn":"false","id":6,"sort":6,"name":"countryCity","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":7,"sort":7,"name":"paymentPassword","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":8,"sort":8,"name":"defaultLocale","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":9,"sort":9,"name":"mainCurrency","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":10,"sort":10,"name":"303","isRequired":"2","isRegField":"1","status":"1"},{"bulitIn":"false","id":11,"sort":11,"name":"201","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":12,"sort":12,"name":"nickName","isRequired":"2","isRegField":"1","status":"1"},{"bulitIn":"false","id":13,"sort":13,"name":"sex","isRequired":"2","isRegField":"1","status":"1"},{"bulitIn":"false","id":14,"sort":14,"name":"302","isRequired":"2","isRegField":"1","status":"1"},{"bulitIn":"false","id":15,"sort":15,"name":"110","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":16,"sort":16,"name":"birthday","isRequired":"2","isRegField":"1","status":"1"},{"bulitIn":"false","id":17,"sort":17,"name":"realName","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":18,"sort":18,"name":"301","isRequired":"2","isRegField":"1","status":"1"},{"bulitIn":"false","id":19,"sort":19,"name":"serviceTerms","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":20,"sort":20,"name":"securityIssues","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":21,"sort":21,"name":"resource","isRequired":"2","isRegField":"1","status":"0"},{"bulitIn":"false","id":22,"sort":22,"name":"constellation","isRequired":"2","isRegField":"2","status":"0"}]' WHERE id = 82;


 select redo_sqls($$
         ALTER TABLE "pay_account" ADD COLUMN "frozen_time" timestamp(6);
         COMMENT ON COLUMN "pay_account"."frozen_time" IS '冻结时间';
      $$);