-- auto gen by sh $now by cj
-- init Deposit Account Warning data in sys_param
-- auto gen by sh $now by cj
-- init Deposit Account Warning data in sys_param
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'safe.max.val', '', '60', '1', '安全范围最大值', '', 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'orange.warning.max.val', '', '80', '2', '橙色预警最大值', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'orange.warning.alert.val', '', '61', '3', '橙色预警提醒值', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'red.warning.alert.val', '', '81', '4', '红色预警提醒值', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'orange.warning.type', '1', '1', '5', '橙色预警提示方式', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'red.warning.type', '3', '3', '6', '红色预警提示方式', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'freeze.warning.type', '3', '3', '7', '账户冻结提醒方式', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'inadequate.warning.count', '2', '2', '8', '层级账户不足个数', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'inadequate.warning.state', 'true', 'true', '9', '层级账户不足提醒', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'depositAccountWarning', 'deposit.reset.days', '1', '1', '10', '账户入款清零时间/天', NULL, 't', NULL);

INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'safe.max.val', '', '60', '1', '安全范围最大值', '', 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'orange.warning.max.val', '', '80', '2', '橙色预警最大值', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'orange.warning.alert.val', '', '61', '3', '橙色预警提醒值', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'red.warning.alert.val', '', '81', '4', '红色预警提醒值', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'orange.warning.type', '1', '1', '5', '橙色预警提示方式', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'red.warning.type', '3', '3', '6', '红色预警提示方式', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'freeze.warning.type', '3', '3', '7', '账户冻结提醒方式', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'unusual.warning.type', '3', '3', '8', '账户异常提醒方式', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'inadequate.warning.count', '2', '2', '9', '层级账户不足个数', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'inadequate.warning.state', 'true', 'true', '10', '层级账户不足提醒', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'deposit.reset.days', '1', '1', '11', '账户入款清零时间/天', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'unusual.error.notice.val', '', '', '12', 'X小时内X个玩家对某收款账户失败达到X次时进行提醒', NULL, 'f', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('content', 'payAccountWarning', 'unusual.noincome.notice.val', '', '', '13', 'X小时内次某收款账号没有存款成功的订单时提醒', NULL, 'f', NULL);

INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'apportionSetting', 'agent.rakeback.percent', '', '', '1', '优惠分摊设置-代理-返水优惠分摊比例', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'apportionSetting', 'agent.preferential.percent', '', '', '2', '优惠分摊设置-代理-优惠活动分摊比例', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'apportionSetting', 'agent.poundage.percent', '', '', '3', '优惠分摊设置-代理-手续费分摊比例', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'apportionSetting', 'topagent.rakeback.percent', '', '', '4', '优惠分摊设置-总代-返水优惠分摊比例', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'apportionSetting', 'topagent.preferential.percent', '', '', '5', '优惠分摊设置-总代-优惠活动分摊比例', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'apportionSetting', 'topagent.poundage.percent', '', '', '6', '优惠分摊设置-总代-手续费分摊比例', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'apportionSetting', 'topagent.rebate.percent', '', '', '7', '优惠分摊设置-总代-佣金分摊比例', NULL, 't', NULL);

INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'rakebackSetting', 'settlement.period.times', '', '', '0', '返水设置-结算周期-每月次数', NULL, 't', NULL);
INSERT INTO "sys_param" ("module", "param_type", "param_code", "param_value", "default_value", "order_num", "remark", "parent_code", "active", "site_id") VALUES ('setting', 'rebateSetting', 'settlement.period.times', '', '', '0', '返佣设置-结算周期-每月次数', NULL, 't', NULL);
