-- auto gen by tom 2015-09-18 09:18:43
-- 偏好设置系统提示音系统参数值
INSERT INTO sys_param(module,param_type,param_code,param_value,default_value,order_num,remark,parent_code, active,site_id ) select 'setting', 'sys_warming_tone_project', 'default', 'settingTone/59/1440061861757.wav', '1000ms', 1, '系统默认', NULL, 't', NULL  where (select count(1) from sys_param where  module='setting' and param_type='sys_warming_tone_project' and param_code='default')<1;
INSERT INTO sys_param(module,param_type,param_code,param_value,default_value,order_num,remark,parent_code, active,site_id ) select 'setting', 'sys_warming_tone_project', 'bird', 'settingTone/59/1440061861757.wav', '2000ms', 2, '清脆鸟声', NULL, 't', NULL  where (select count(1) from sys_param where  module='setting' and param_type='sys_warming_tone_project' and param_code='bird')<1;
INSERT INTO sys_param(module,param_type,param_code,param_value,default_value,order_num,remark,parent_code, active,site_id ) select 'setting', 'sys_warming_tone_project', '3D', 'settingTone/59/1440061861757.wav', '3000ms', 3, '3D和弦', NULL, 't', NULL  where (select count(1) from sys_param where  module='setting' and param_type='sys_warming_tone_project' and param_code='3D')<1;
INSERT INTO sys_param(module,param_type,param_code,param_value,default_value,order_num,remark,parent_code, active,site_id ) select 'setting', 'sys_warming_tone_project', 'water', 'settingTone/59/1440061861757.wav', '1500ms', 4, '流水声', NULL, 't', NULL  where (select count(1) from sys_param where  module='setting' and param_type='sys_warming_tone_project' and param_code='water')<1;
INSERT INTO sys_param(module,param_type,param_code,param_value,default_value,order_num,remark,parent_code, active,site_id ) select 'setting', 'sys_warming_tone_project', 'bruce', 'settingTone/59/1440061861757.wav', '2000ms', 5, '布鲁斯', NULL, 't', NULL  where (select count(1) from sys_param where  module='setting' and param_type='sys_warming_tone_project' and param_code='bruce')<1;
INSERT INTO sys_param(module,param_type,param_code,param_value,default_value,order_num,remark,parent_code, active,site_id ) select 'setting', 'sys_warming_tone_project', 'orchestral', 'settingTone/59/1440061861757.wav', '2000ms', 6, '管弦乐', NULL, 't', NULL  where (select count(1) from sys_param where  module='setting' and param_type='sys_warming_tone_project' and param_code='orchestral')<1;

